version: "3"
services:
  python:
    build: .   
    env_file: .env
    container_name: parkingPython
    restart: always
    environment:   
      TZ: Europe/Madrid
    networks:   
      - web     
networks:
  web:
    external: true